services:
  comfyui-worker:
    image: runpod-worker-comfy:latest
    pull_policy: never
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - SERVE_API_LOCALLY=true
    ports:
      - 8000:8000
      - 8188:8188
    volumes:
      - ./data/comfyui/output:/comfyui/output
      - ./data/comfyui/custom_nodes:/comfyui/custom_nodes
      - ./data/comfyui/models/models:/comfyui/models
      - ./data/runpod-volume:/runpod-volume